### PR TITLE
Add Favicon interface

### PR DESCRIPTION
**Pull request by ghost**
Add the favicon interface for the icon in the server list

### CODE REVIEW

**Comment by TheElectronWill** [comment]
Why add an `addPlayer` method ? Maybe it shouldn't be in the API, because the player's list storage is implementation-dependant. Moreover, why did all the lines change?
For the favicon, I think that it would be better to put 2 methods in the server: `setFavicon(BufferedImage)` and `setFavicon(String)`.

**Comment by ghost** [comment]
For the addPlayer it was for test sorry. All the lines change because the class wasn't before in UTF-8.
Okay so the Favicon interface isn't util ?

**Comment by TheElectronWill** [comment]
Yeah, the Favicon interface is completely useless.

**Comment by ghost** [comment]
The Favicon interface is useless so i close the pull request

**Pull request closed without merging**
