### PR TITLE
Verification of all clientbound packets.

### PR DESCRIPTION
**Pull request by ghost**
I verified all clientbound packets and there were many little things to
change and the ClientStatusPacket is serverbound and not clientbound.

### CODE REVIEW

**Comment by TheElectronWill** [comment]
You're right the ClientStatusPacket is serverbound, my mistake.
Don't use `entityID` but `entityId` (same for blockId and any xxId), as recommended by the java naming convention, and by everyone: http://stackoverflow.com/questions/2236807/java-naming-convention-with-acronyms?rq=1

**Comment by TheElectronWill** [comment]
Also, some conditions are weird, aren't they?
`2000 <= effectID && effectID <= 2002`

**Comment by TheElectronWill** [comment]
I think we should leave `deltaX` instead of `xDelta`, because that's how we use it in science (maths and physics in particular): Δx
But if you have arguments for xΔ I'm open to discussion.

**Comment by ghost** [comment]
The ClientStatusPacket is a serverbound packet. For the ID it's an habit i have so i will change this tomorrow. The condition in the EffectPacket is normal see [here](http://wiki.vg/Protocol#Effect). And for xDelta i see it in many class from Maaattt.

**Comment by TheElectronWill** [comment]
Oh yes, I misunderstood the condition, because of the order. `effectId >= 2000 && effectId <= 2002` yes that's correct :)
Maat uses `xVelocity` and `deltaX` is used everywhere. xVelocity, velocityX, that's not a big difference, but since deltaX is more natural, I think that we should be coherent and use that naming scheme (deltaX, speedX or velocityX, etc.) everywhere.

**Comment by ghost** [comment]
I corrected all variable names i think you can merge the pull request.

**Pull request merged**
